### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by pdclark** [ranjangoyal/rtcamp#1]
https://github.com/ranjangoyal/rtcamp/blob/main/ajax_process.php#L2
https://github.com/ranjangoyal/rtcamp/blob/main/config.php#L27-L30
https://github.com/ranjangoyal/rtcamp/blob/main/index.php#L2
https://github.com/ranjangoyal/rtcamp/blob/main/index.php#L18
https://github.com/ranjangoyal/rtcamp/blob/main/send_emails_new.php#L10-L13
https://github.com/ranjangoyal/rtcamp/blob/main/includes/header.php#L2
- [ ] Use single-quotes if not parsing variables in strings in PHP.
- [ ] Don't use parenthesis with `include/require`. It's a language construct, not a function.
- [ ] Use `__DIR__` when using `require` or `include`. Starting from current directory scans all folders in `include_path`.

https://github.com/ranjangoyal/rtcamp/blob/main/ajax_process.php#L5
https://github.com/ranjangoyal/rtcamp/blob/main/ajax_process.php#L11
https://github.com/ranjangoyal/rtcamp/blob/main/config.php#L4-L6
https://github.com/ranjangoyal/rtcamp/blob/main/config.php#L16
https://github.com/ranjangoyal/rtcamp/blob/main/config.php#L36
https://github.com/ranjangoyal/rtcamp/blob/main/index.php#L2-L18
https://github.com/ranjangoyal/rtcamp/blob/main/send_emails_new.php#L2
https://github.com/ranjangoyal/rtcamp/blob/main/send_emails_new.php#L19
https://github.com/ranjangoyal/rtcamp/blob/main/send_emails_new.php#L40-L100
https://github.com/ranjangoyal/rtcamp/blob/main/send_emails_new.php#L148
https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsValidation.php#L6-L44
https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsNewsletters.php#L28-L42
https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsNewsletters.php#L50
https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsNewsletters.php#L71-L130
https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsNewsletters.php#L169-L173
https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsNewsletters.php#L186-L188
https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsNewsletters.php#L195
- [ ] Use single-quotes if not parsing variables in strings in PHP.

https://github.com/ranjangoyal/rtcamp/blob/main/send_emails_new.php#L127
- [ ] "GitHub" not "Github"

https://github.com/ranjangoyal/rtcamp/blob/main/send_emails_new.php#L134-L135
- [ ] From name and addresses should be set in config.

https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsDatabase.php#L149-L152
- [ ] Don't commit credentials to the repo. Set examples.

https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsNewsletters.php#L8
- [ ] "unsubscribe" not "Un subscribe"

https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsNewsletters.php#L155
- [ ] Unsubscribe/subscribe without verification token allows anyone to unsubscribe/subscribe any email.

https://github.com/ranjangoyal/rtcamp/blob/main/classes/clsNewsletters.php#L169-L173
- [ ] Should this function be `return`ing HTML or `echo`ing HTML?

**Comment by pdclark** [comment]
Looks good! Some minor notes:

https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/includes/header.php#L2
- Should be `require_once dirname( __DIR__ ) . '/config.php'`

https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/index.php#L2
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/index.php#L19
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/ajax_process.php#L2
- Use `__DIR__` when using `require` or `include`. Starting from current directory scans all folders in `include_path`.

https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/send_emails_new.php#L4-L5
- Should be: 
```define('PATH_MAINFS', __DIR__ ); 
define('PATH_MAIN', $_SERVER['HTTPS'] == 'on' ? 'https://' . $_SERVER['HTTP_HOST'] : 'http://' . $_SERVER['HTTP_HOST'] );```

https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/config.php#L10-L18
- Don't hard-code the server protocol. See `$_SERVER['HTTPS']`.

https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/send_emails_new.php#L12-L15
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/config.php#L29-L32
- Don't use parenthesis with `include/require`. It's a language construct, not a function.

https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/send_emails_new.php#L21-L23
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/ajax_process.php#L23-L27
- Leave commented code out of the repo.

https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/send_emails_new.php#L29-L89
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/send_emails_new.php#L97-L103
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/send_emails_new.php#L125
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/send_emails_new.php#L128
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsDatabase.php#L16
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsDatabase.php#L29
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsDatabase.php#L59
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsDatabase.php#L74
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsDatabase.php#L134
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L6
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L35
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L88
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L100
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L114
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L138
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L160
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L175
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L178-L183
https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsNewsletters.php#L187-L192
- Use single-quotes if not parsing variables or `\r\n` in strings in PHP.

https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsDatabase.php#L149
- Don't commit credentials to the repo. Set examples.

https://github.com/ranjangoyal/rtcamp/blob/e0f101c20feed1cd8b59cc8686a8ef4f1051074e/classes/clsValidation.php#L16
- See `filter_var()` and `FILTER_SANITIZE_EMAIL`.

**Comment by ranjangoyal** [comment]
All points are taken care of. Please review
